services:
  - type: static_site
    name: front-control-red
    repo: https://github.com/JOEL0316/Front-Contol-Red
    branch: master
    buildCommand: yarn install && yarn build
    publishPath: public
    envVars:
      - key: NODE_VERSION
        value: 16