services:
  - type: web_service
    name: front-control-red
    repo: https://github.com/JOEL0316/Front-Contol-Red
    branch: master
    buildCommand: npm install && npm run build
    publishPath: public
    envVars:
      - key: NODE_VERSION
        value: 16



